name: tdd_tutorial
description: A Flutter App made in the course "Flutter Firebase Test Driven Development And Clean Architecture" by Dastagir Ahmed (dbestech / Udemy).
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  dartz: ^0.10.1
  http: ^1.1.0
  flutter_bloc: ^9.1.0
  bloc: ^9.0.0
  get_it: ^8.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  mocktail: ^1.0.3
  bloc_test: ^10.0.0

dependency_overrides:
  async: ^2.13.0
  material_color_utilities: ^0.12.0
  fake_async: ^1.3.3
  leak_tracker: ^10.0.9
  vm_service: ^15.0.0

flutter:

  uses-material-design: true